--------------------------------------------------------
--  DDL for Table Z_SRC_USER
--------------------------------------------------------

  CREATE TABLE "MX"."Z_SRC_USER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(3,0), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TEL" NUMBER(16,0), 
	"CREATION_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALDB" ;
