--------------------------------------------------------
--  Constraints for Table Z_SRC_USER
--------------------------------------------------------

  ALTER TABLE "MX"."Z_SRC_USER" ADD CONSTRAINT "PK_Z_SRC_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOCALDB"  ENABLE;
